# Generated by Django 5.0.1 on 2024-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Phone', models.IntegerField(default='')),
                ('Email', models.EmailField(default='', max_length=50)),
                ('EventDate', models.DateField(default='', max_length=15)),
                ('Venue', models.CharField(default='', max_length=100)),
                ('TypeofEvent', models.CharField(default='', max_length=100)),
                ('Messege', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
